# Generated by Django 5.2.9 on 2025-12-31 12:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JudicialAuthority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="code"
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
            ],
            options={
                "verbose_name": "JudicialAuthority",
                "verbose_name_plural": "JudicialAuthorities",
            },
        ),
        migrations.CreateModel(
            name="JudicialGeometry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=511, verbose_name="name")),
                (
                    "code",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="code"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=511, null=True, verbose_name="address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326, verbose_name="geometry"
                    ),
                ),
                (
                    "judicial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geometries",
                        to="court.judicialauthority",
                        verbose_name="judicial",
                    ),
                ),
            ],
            options={
                "verbose_name": "JudicialGeometry",
                "verbose_name_plural": "JudicialGeometries",
            },
        ),
    ]
