# Generated by Django 5.2.9 on 2025-12-31 12:30

from django.db import migrations
from django.db.models import Max

DEFAULT_JUDICIAL_AUTHORITIES = [
    "دادگاه حقوقی",
    "دادسرا",
    "دادگاه کیفری",
    "دادگاه صلح حقوقی",
    "دادگاه صالح کیفری",
    "دادگاه خانواده",
    "کلانتری",
]


def create_default_judicial_authorities(apps, _):
    JudicialAuthority = apps.get_model("court", "JudicialAuthority")
    last_code = (
        JudicialAuthority.objects.aggregate(max_code=Max("code")).get("max_code")
    ) or 999

    for name in DEFAULT_JUDICIAL_AUTHORITIES:
        obj, created = JudicialAuthority.objects.get_or_create(
            name=name, defaults={"code": last_code + 1}
        )
        if created:
            last_code += 1


class Migration(migrations.Migration):

    dependencies = [
        ("court", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_judicial_authorities),
    ]
